export const BASE_URL = 'https://api.themoviedb.org/3'
export const MOVIE_URL = BASE_URL + '/movie'
export const NOW_PLAYING_MOVIE_URL = MOVIE_URL + '/now_playing'
export const POPULAR_MOVIE_URL = MOVIE_URL + '/popular'
export const TOP_RATED_MOVIE_URL = MOVIE_URL + '/top_rated'
export const POSTER_URL = 'https://image.tmdb.org/t/p/w500'
export const BACKDROP_URL ='https://image.tmdb.org/t/p/original'
export const SEARCH_URL = BASE_URL + '/search'
export const IMG_URL ='https://image.tmdb.org/t/p/original'
export const IMG_SMALL_URL ='https://image.tmdb.org/t/p/t/p/w150_and_h225_bestv2'
export const IMG_BIG_URL ='https://image.tmdb.org/t/p/w500'
export const PERSON_URL =BASE_URL + '/person'

